#!/bin/bash 
#kasutaja lisamine failist
if [ $# -ne 1 ]; then
	echo "kasutusjuhend: $0 failinimi"
else
	failinimi=$1
	if [ -f $failnimi ]; then
	echo "fail korras"
	for nimi in $(cat $failinimi)
	do
		kasutajanimi=$(echo "$rida" | cut -fl -d:)
		sh kasutaja_lisamine $kasutajanimi
		echo "$rida" | chpasswd 
	done
	else
		echo " probleem failiga $failinimi"
	fi
fi
	
